export enum EnterpriseRoute {
  Workspace = '/workspace',
  Chat = '/workspace/chat',
  Platform = '/enterprise/platform',
  Gallery = '/workspace/gallery',
  Agents = '/enterprise/agents',
  Dashboard = '/enterprise/dashboard',
  Persona = '/enterprise/persona',
  ScheduledTasks = '/enterprise/scheduled-tasks',
  Memories = '/enterprise/memories',
  Feedback = '/enterprise/feedback',
  Knowledge = '/enterprise/knowledge',
  GeneralSkills = '/enterprise/general-skills',
  Skills = '/enterprise/skills',
  Tools = '/enterprise/tools',
  Accounts = '/enterprise/accounts',
  Models = '/enterprise/models',
}
